
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutNauka': typeof import("../components/about/AboutNauka.vue")['default']
    'AboutObr': typeof import("../components/about/AboutObr.vue")['default']
    'AboutRabota': typeof import("../components/about/AboutRabota.vue")['default']
    'AboutTop': typeof import("../components/about/AboutTop.vue")['default']
    'ContactBlok': typeof import("../components/layout/ContactBlok.vue")['default']
    'TheAdminHeader': typeof import("../components/layout/TheAdminHeader.vue")['default']
    'TheFooter': typeof import("../components/layout/TheFooter.vue")['default']
    'TheHeader': typeof import("../components/layout/TheHeader.vue")['default']
    'AboutBlok': typeof import("../components/mainpage/AboutBlok.vue")['default']
    'MainBaner': typeof import("../components/mainpage/MainBaner.vue")['default']
    'OtzivBlok': typeof import("../components/mainpage/OtzivBlok.vue")['default']
    'PreimBlok': typeof import("../components/mainpage/PreimBlok.vue")['default']
    'ServicesBlok': typeof import("../components/mainpage/ServicesBlok.vue")['default']
    'ScrollButton': typeof import("../components/ui/ScrollButton.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutNauka': typeof import("../components/about/AboutNauka.vue")['default']
    'LazyAboutObr': typeof import("../components/about/AboutObr.vue")['default']
    'LazyAboutRabota': typeof import("../components/about/AboutRabota.vue")['default']
    'LazyAboutTop': typeof import("../components/about/AboutTop.vue")['default']
    'LazyContactBlok': typeof import("../components/layout/ContactBlok.vue")['default']
    'LazyTheAdminHeader': typeof import("../components/layout/TheAdminHeader.vue")['default']
    'LazyTheFooter': typeof import("../components/layout/TheFooter.vue")['default']
    'LazyTheHeader': typeof import("../components/layout/TheHeader.vue")['default']
    'LazyAboutBlok': typeof import("../components/mainpage/AboutBlok.vue")['default']
    'LazyMainBaner': typeof import("../components/mainpage/MainBaner.vue")['default']
    'LazyOtzivBlok': typeof import("../components/mainpage/OtzivBlok.vue")['default']
    'LazyPreimBlok': typeof import("../components/mainpage/PreimBlok.vue")['default']
    'LazyServicesBlok': typeof import("../components/mainpage/ServicesBlok.vue")['default']
    'LazyScrollButton': typeof import("../components/ui/ScrollButton.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutNauka: typeof import("../components/about/AboutNauka.vue")['default']
export const AboutObr: typeof import("../components/about/AboutObr.vue")['default']
export const AboutRabota: typeof import("../components/about/AboutRabota.vue")['default']
export const AboutTop: typeof import("../components/about/AboutTop.vue")['default']
export const ContactBlok: typeof import("../components/layout/ContactBlok.vue")['default']
export const TheAdminHeader: typeof import("../components/layout/TheAdminHeader.vue")['default']
export const TheFooter: typeof import("../components/layout/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/layout/TheHeader.vue")['default']
export const AboutBlok: typeof import("../components/mainpage/AboutBlok.vue")['default']
export const MainBaner: typeof import("../components/mainpage/MainBaner.vue")['default']
export const OtzivBlok: typeof import("../components/mainpage/OtzivBlok.vue")['default']
export const PreimBlok: typeof import("../components/mainpage/PreimBlok.vue")['default']
export const ServicesBlok: typeof import("../components/mainpage/ServicesBlok.vue")['default']
export const ScrollButton: typeof import("../components/ui/ScrollButton.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutNauka: typeof import("../components/about/AboutNauka.vue")['default']
export const LazyAboutObr: typeof import("../components/about/AboutObr.vue")['default']
export const LazyAboutRabota: typeof import("../components/about/AboutRabota.vue")['default']
export const LazyAboutTop: typeof import("../components/about/AboutTop.vue")['default']
export const LazyContactBlok: typeof import("../components/layout/ContactBlok.vue")['default']
export const LazyTheAdminHeader: typeof import("../components/layout/TheAdminHeader.vue")['default']
export const LazyTheFooter: typeof import("../components/layout/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/layout/TheHeader.vue")['default']
export const LazyAboutBlok: typeof import("../components/mainpage/AboutBlok.vue")['default']
export const LazyMainBaner: typeof import("../components/mainpage/MainBaner.vue")['default']
export const LazyOtzivBlok: typeof import("../components/mainpage/OtzivBlok.vue")['default']
export const LazyPreimBlok: typeof import("../components/mainpage/PreimBlok.vue")['default']
export const LazyServicesBlok: typeof import("../components/mainpage/ServicesBlok.vue")['default']
export const LazyScrollButton: typeof import("../components/ui/ScrollButton.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
